name: clothes_store
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  bloc: ^8.1.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  toggle_switch: ^2.1.0
  flutter_svg: ^2.0.9
  google_sign_in: ^6.1.5
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  intl_phone_number_input: ^0.7.3+1
  line_icons: ^2.0.3
  material3_layout: ^0.0.7
  velocity_x: ^4.1.1
  firebase_database: ^10.3.4
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/